lang: fr
toc-title: "Contenu de la note"
author-title: "Auteur"
number-sections: true
format:
  html:
    page-layout: full
    grid:
      sidebar-width: 400px
      margin-width: 400px
      gutter-width: 2em
      body-width: 1120px
    include-before-body: "header.html"
    css: "notebook_linkpact.css" # custom colors and fontsizes for html
    toc: true
    toc-location: left
    toc-depth: 3
    number-depth: 3 # numbering up to sections/subsections/subsubsections (1/2/3)
    html-math-method: mathjax
    embed-resources: true
    link-external-newwindow: true
    
crossref: 
  title-delim: "&nbsp;:"
    
execute:
  include: true
  echo: false
  warning: false
  message: false